"""delete redundant unique keys

Revision ID: 6d35dbab87bc
Revises: 02bada9d5222
Create Date: 2022-11-12 15:18:07.545991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d35dbab87bc'
down_revision = '02bada9d5222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workers_birthday_key', 'workers', type_='unique')
    op.drop_constraint('workers_father_name_key', 'workers', type_='unique')
    op.drop_constraint('workers_first_name_key', 'workers', type_='unique')
    op.drop_constraint('workers_last_name_key', 'workers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('workers_last_name_key', 'workers', ['last_name'])
    op.create_unique_constraint('workers_first_name_key', 'workers', ['first_name'])
    op.create_unique_constraint('workers_father_name_key', 'workers', ['father_name'])
    op.create_unique_constraint('workers_birthday_key', 'workers', ['birthday'])
    # ### end Alembic commands ###
