"""alter orders

Revision ID: c6bc4cf2a55d
Revises: 6d35dbab87bc
Create Date: 2022-11-12 18:37:43.916349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bc4cf2a55d'
down_revision = '6d35dbab87bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###
