from .provider_resource import ProviderDetailResource, ProviderListResource
from .position_resource import PositionDetailResource, PositionListResource
from .product_resource import ProductDetailResource, ProductListResource
from .user_resource import UserDetailResource, UserListResource
from .worker_resource import WorkerDetailResource, WorkerListResource
from .order_resource import OrderDetailResource, OrderListResource
